# Generated by Django 2.2.8 on 2020-09-13 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 1, 48, 3, 604598)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 13, 1, 48, 27, 995385)),
            preserve_default=False,
        ),
    ]
