# Generated by Django 3.1.2 on 2020-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201006_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='one_click_processing',
            field=models.BooleanField(default=False),
        ),
    ]
