# Generated by Django 2.2.8 on 2020-09-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percentage_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
