# Generated by Django 2.2.8 on 2020-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200926_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_tag',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('F', 'Featured'), ('B', 'bestseller')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
